name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Run tests
      run: |
        # Add your test commands here
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment runs after the build job

    steps:
    - name: Notify deployment webhook
      env:
        DEPLOYMENT_WEBHOOK_URL: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"status": "deploying"}' $DEPLOYMENT_WEBHOOK_URL

    - name: Deploy application
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        # Add deployment commands here
        echo "Deploying application..."
        # Example: SSH into a server or trigger a deployment script
        ssh user@your-server "cd /path/to/app && git pull && systemctl restart your-app"

    - name: Notify deployment success
      env:
        DEPLOYMENT_WEBHOOK_URL: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"status": "success"}' $DEPLOYMENT_WEBHOOK_URL